version: '3'
services:
  mysql_db:
    image: mysql:latest
    restart: always
    networks:
        - app_tier
    volumes:
        - ./mysql/db:/var/lib/mysql
    ports:
        - "3306:3306"
    cap_add:
        - SYS_NICE
    environment:
        - MYSQL_DATABASE=app
        - MYSQL_USER=user
        - MYSQL_PASSWORD=1234
        - MYSQL_ROOT_PASSWORD=1234

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    stdin_open: true 
    restart: always
    networks:
        - app_tier
    volumes:
       - ./frontend:/usr/src/app/frontend
       - /usr/src/app/frontend/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: backend
    restart: always 
    links:
        - mysql_db:mysql_db 
    depends_on:
        - mysql_db
    networks:
        - app_tier
    volumes:
       - ./backend/web:/app        
    command: gunicorn -w 1 -b 0.0.0.0:5000 run:app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks: 
      - app_tier
    restart: "on-failure"

networks:  # 네트워크 이름 
  app_tier:
    driver: bridge  # 컨테이너를 bridge로 연결 